/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapIndexRouteImport } from './routes/sitemap.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SitemapServicesRouteImport } from './routes/sitemap.services'
import { Route as SitemapPostsRouteImport } from './routes/sitemap.posts'
import { Route as SitemapPagesRouteImport } from './routes/sitemap.pages'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexRoute = SitemapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitemapRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapServicesRoute = SitemapServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SitemapRoute,
} as any)
const SitemapPostsRoute = SitemapPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => SitemapRoute,
} as any)
const SitemapPagesRoute = SitemapPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => SitemapRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sitemap': typeof SitemapRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sitemap/pages': typeof SitemapPagesRoute
  '/sitemap/posts': typeof SitemapPostsRoute
  '/sitemap/services': typeof SitemapServicesRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/sitemap/': typeof SitemapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sitemap/pages': typeof SitemapPagesRoute
  '/sitemap/posts': typeof SitemapPostsRoute
  '/sitemap/services': typeof SitemapServicesRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/sitemap': typeof SitemapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/sitemap': typeof SitemapRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/sitemap/pages': typeof SitemapPagesRoute
  '/sitemap/posts': typeof SitemapPostsRoute
  '/sitemap/services': typeof SitemapServicesRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/sitemap/': typeof SitemapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/sitemap'
    | '/testimonials'
    | '/blog/$slug'
    | '/services/$slug'
    | '/sitemap/pages'
    | '/sitemap/posts'
    | '/sitemap/services'
    | '/blog/'
    | '/services/'
    | '/sitemap/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/testimonials'
    | '/blog/$slug'
    | '/services/$slug'
    | '/sitemap/pages'
    | '/sitemap/posts'
    | '/sitemap/services'
    | '/blog'
    | '/services'
    | '/sitemap'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/sitemap'
    | '/testimonials'
    | '/blog/$slug'
    | '/services/$slug'
    | '/sitemap/pages'
    | '/sitemap/posts'
    | '/sitemap/services'
    | '/blog/'
    | '/services/'
    | '/sitemap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  SitemapRoute: typeof SitemapRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/': {
      id: '/sitemap/'
      path: '/'
      fullPath: '/sitemap/'
      preLoaderRoute: typeof SitemapIndexRouteImport
      parentRoute: typeof SitemapRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/services': {
      id: '/sitemap/services'
      path: '/services'
      fullPath: '/sitemap/services'
      preLoaderRoute: typeof SitemapServicesRouteImport
      parentRoute: typeof SitemapRoute
    }
    '/sitemap/posts': {
      id: '/sitemap/posts'
      path: '/posts'
      fullPath: '/sitemap/posts'
      preLoaderRoute: typeof SitemapPostsRouteImport
      parentRoute: typeof SitemapRoute
    }
    '/sitemap/pages': {
      id: '/sitemap/pages'
      path: '/pages'
      fullPath: '/sitemap/pages'
      preLoaderRoute: typeof SitemapPagesRouteImport
      parentRoute: typeof SitemapRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface SitemapRouteChildren {
  SitemapPagesRoute: typeof SitemapPagesRoute
  SitemapPostsRoute: typeof SitemapPostsRoute
  SitemapServicesRoute: typeof SitemapServicesRoute
  SitemapIndexRoute: typeof SitemapIndexRoute
}

const SitemapRouteChildren: SitemapRouteChildren = {
  SitemapPagesRoute: SitemapPagesRoute,
  SitemapPostsRoute: SitemapPostsRoute,
  SitemapServicesRoute: SitemapServicesRoute,
  SitemapIndexRoute: SitemapIndexRoute,
}

const SitemapRouteWithChildren =
  SitemapRoute._addFileChildren(SitemapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  SitemapRoute: SitemapRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
